#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-2604"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3dec12b4e3704a07af8dac742376073b" }
]

[assets]
directory = "./public"
